In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.model_selection import cross_val_score,cross_val_predict
pd.options.display.width = 0

In [7]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [8]:
import os
path = "/content/gdrive/My Drive/Colab Notebooks/m2-proba-finance-2019"
os.listdir("./")


['.config', 'gdrive', 'sample_data']

In [0]:
D_author = pd.read_csv( path+"/authorData.csv")

In [2]:
D_author = pd.read_csv("authorData.csv")

In [3]:
cols = D_author.columns
cols

Index(['engagement', 'timestamp', 'language', 'feature1', 'feature2',
       'followers', 'author', 'word_count', 'shared_url_count',
       'shared_url_domain', 'is_reply', 'is_retweet', 'contains_video',
       'contains_image'],
      dtype='object')

In [4]:
D_author.shape

(629877, 14)

In [5]:
D_author.head()

engagement      timestamp language  feature1  feature2  followers  \
0           0  1655713481254       en       100         0        999   
1           0  1655743160254       en       100        -5          5   
2        3486  1655395750254       en       100        -5     454592   
3           7  1654621088254       ar       100         5      19348   
4           0  1655754531254       en        45        -5        973   

                             author  word_count  shared_url_count  \
0  d2e03f4b7a57a6828392a80b6d8667c3          25                 0   
1  5622c71671e9b0ab9052fd574876b46d           9                 0   
2  9b72b401edaf6aec6603856a3a6fb050          45                 0   
3  dc3d6148b435c40a4e75e7d6b5bd22c9          10                 0   
4  0e47c55a7918dd9130da37a80e46a2e0          14                 0   

  shared_url_domain  is_reply  is_retweet  contains_video  contains_image  
0               NaN     False        True            True           False  
1               NaN     False       False           False           False  
2               NaN     False       False           False           False  
3               NaN     False       False           False           False  
4               NaN     False        True           False            True

In [0]:
D_train = pd.read_csv(path+"/train.csv")

In [6]:
D_train = pd.read_csv("train.csv")

In [7]:
D_train.head()

engagement      timestamp language  feature1  feature2  followers  \
0          15  1655784230254       en        73         0        696   
1           0  1655789734254       en        58         0       1268   
2       91007  1655599613254       en       100         5      17526   
3           3  1655788872254       en         0        -5        239   
4          11  1655788810254       en       100        -5      21531   

                             author  word_count  shared_url_count  \
0  bd20432d80dfe4825a7a106312bda52e          18                 0   
1  1016de41efe1384efac491c1514da67c          13                 1   
2  71e2ecc6cc1d6515a6b122fab4c63bfc          15                 0   
3  2a9109f38d90a2a96e284a07c1a57e9b           8                 0   
4  efea6800044f4b9b1df1d74031b4e027          49                 0   

    shared_url_domain  ...     V1015     V1016     V1017     V1018     V1019  \
0                 NaN  ...  0.066302 -0.002309  0.006296 -0.003366  0.055845   
1  http://fllwrs.com/  ...  0.028814  0.009487 -0.000962  0.003516  0.001307   
2                 NaN  ...  0.020109  0.014174  0.019271  0.011605 -0.001049   
3                 NaN  ...  0.069541  0.094191 -0.002353  0.030343  0.004930   
4                 NaN  ...  0.040541  0.022897  0.003639  0.002614 -0.000489   

      V1020     V1021     V1022     V1023     V1024  
0  0.002813  0.030930  0.040009  0.017094  0.047829  
1 -0.000108  0.036496  0.020098  0.018320  0.033285  
2  0.018731  0.008732  0.034822  0.042102  0.020760  
3  0.000064  0.007801  0.006239  0.020304  0.032962  
4  0.006744  0.031689  0.018264  0.010356  0.024227  

[5 rows x 1038 columns]

In [8]:
D_train.shape

(5536, 1038)

In [89]:
a = np.sort(D_train.drop(cols, axis=1).apply(lambda x: x.corr(D_train.engagement)))

In [92]:
np.set_printoptions(threshold=np.inf)
print(a)

[-9.52478904e-02 -9.16575920e-02 -8.40366421e-02 -8.31602299e-02
 -8.02303082e-02 -7.63369470e-02 -7.24076306e-02 -7.16053356e-02
 -7.08228439e-02 -6.91140556e-02 -6.77888684e-02 -6.44377376e-02
 -6.25780610e-02 -5.97483128e-02 -5.88288260e-02 -5.88261377e-02
 -5.84180872e-02 -5.82638433e-02 -5.80358323e-02 -5.72896158e-02
 -5.69959519e-02 -5.69870149e-02 -5.67783791e-02 -5.65760521e-02
 -5.61632015e-02 -5.51836711e-02 -5.39807404e-02 -5.35680039e-02
 -5.27998348e-02 -5.17237730e-02 -5.13782420e-02 -5.13595593e-02
 -5.11753828e-02 -5.02604475e-02 -5.01277186e-02 -5.00123320e-02
 -4.93957606e-02 -4.80655238e-02 -4.79364089e-02 -4.72380188e-02
 -4.63299333e-02 -4.61385988e-02 -4.50218535e-02 -4.47017065e-02
 -4.46786985e-02 -4.44455207e-02 -4.43471026e-02 -4.42761507e-02
 -4.41073339e-02 -4.39022907e-02 -4.38226122e-02 -4.32012999e-02
 -4.31926250e-02 -4.31022478e-02 -4.23725229e-02 -4.23117340e-02
 -4.22211052e-02 -4.21854317e-02 -4.17861455e-02 -4.16844189e-02
 -4.13760618e-02 -4.10177

In [94]:
X.apply(lambda x: x.corr(D_X.engagement))

feature1              -0.003124
feature2              -0.009128
followers              0.175782
word_count             0.005364
shared_url_count      -0.009132
is_reply              -0.053136
is_retweet            -0.046675
contains_video         0.047084
contains_image        -0.002648
language_popularity    0.010528
avg_engage_language    0.024721
author_popularity     -0.080551
avg_engage_author      0.597416
url_popularity        -0.004891
avg_engage_url         0.112488
dtype: float64

In [0]:
D_test = pd.read_csv(path+"/test.csv")

In [9]:
D_test = pd.read_csv("test.csv")

In [10]:
D_test.head()

Id      timestamp language  feature1  feature2  followers  \
0   1  1655750787254       en       100        -5       3562   
1   2  1655788783254       en        13        -5      13609   
2   3  1655789562254       en       100         0      49903   
3   4  1655665563254       en        95        -5      29317   
4   5  1655789291254       en       100         0        154   

                             author  word_count  shared_url_count  \
0  6dab33d47b0dd5d030e207261f93c319           6                 0   
1  f4dfaa9431bb01891104048b8d2b2cba           7                 0   
2  70b84c15b524cf19cfee948a1357d44a          12                 0   
3  17489c483613cc56ad60d5c7c43b3746          22                 1   
4  5bc44ed424919266ebf344081fdea1a8           3                 0   

  shared_url_domain  ...     V1015     V1016     V1017     V1018     V1019  \
0               NaN  ...  0.001071  0.011511  0.005093  0.014162  0.012245   
1               NaN  ...  0.060200  0.035142  0.017822  0.010709  0.002361   
2               NaN  ...  0.044783 -0.001629 -0.001456  0.005705  0.003102   
3   http://wsj.com/  ...  0.040958  0.013183 -0.002016  0.026362  0.035867   
4               NaN  ...  0.018229  0.025770 -0.000291  0.001325 -0.000563   

          V1020     V1021     V1022     V1023     V1024  
0  3.456288e-03  0.036079  0.043002  0.014374  0.016828  
1  1.209493e-03  0.031409  0.046286  0.013817  0.037918  
2  6.022647e-07  0.032912  0.033760  0.020529  0.044053  
3  9.164630e-03  0.022843  0.045851  0.028039  0.021808  
4  1.361860e-03  0.020734  0.036191  0.006318  0.020059  

[5 rows x 1038 columns]

In [11]:
Y = np.concatenate( [ D_author["engagement"].to_numpy(), D_train["engagement"].to_numpy() ] )

In [12]:
X = pd.concat( [ D_author[cols[1:]], D_train[cols[1:]] ] )
X.fillna("",inplace=True)
D_X = pd.concat( [ D_author[cols], D_train[cols] ] )
D_X.fillna("",inplace=True)

In [13]:
dict_language = dict(X["language"].value_counts())
language_engagement = {}
def freq_count(row, col, dic):
    dic[row[col]] = dic.get(row[col],0) + row["engagement"]
    return
_= D_X.apply( freq_count ,axis=1, args=("language",language_engagement))
average_engage = {}
for key, value in dict_language.items():
    average_engage[key] = language_engagement[key]/value

In [14]:
global_lang_avg_pop = np.mean(list(dict_language.values()))
global_avg_engage_lang = np.mean(list(average_engage.values()))

In [15]:
X["language_popularity"] = X.apply(lambda row: dict_language[row["language"]],axis = 1)
X["avg_engage_language"] = X.apply(lambda row: average_engage[row["language"]],axis = 1)

In [16]:
dict_author = dict(X["author"].value_counts())
author_engagement = {}
_= D_X.apply( freq_count ,axis=1, args=("author",author_engagement))
avg_engage_author = {}
for key, value in dict_author.items():
    avg_engage_author[key] = author_engagement[key]/value

In [17]:
global_author_avg_pop = np.mean(list(dict_author.values()))
global_avg_engage_author = np.mean(list(avg_engage_author.values()))

In [18]:
X["author_popularity"] = X.apply(lambda row: dict_author[row["author"]],axis = 1)
X["avg_engage_author"] = X.apply(lambda row: avg_engage_author[row["author"]],axis = 1)

In [19]:
dict_url = dict(X["shared_url_domain"].value_counts())
url_engagement = {}
_= D_X.apply( freq_count ,axis=1, args=("shared_url_domain",url_engagement))
avg_engage_url = {}
for key, value in dict_url.items():
    avg_engage_url[key] = url_engagement[key]/value

In [20]:
X["has_url"] = X.apply(lambda row: 0 if row["shared_url_domain"] == "" else 1,axis = 1)
X["url_popularity"] = X.apply(lambda row: dict_url[row["shared_url_domain"]] if row["has_url"] else 0,axis = 1)
X["avg_engage_url"] = X.apply(lambda row: avg_engage_url[row["shared_url_domain"]] if row["has_url"] else 0,axis = 1)

In [21]:
boolean_cols = ["is_reply", "is_retweet", "contains_video", "contains_image"]
X[boolean_cols] = X[boolean_cols].astype(int)

In [22]:
dropped_cols = ["language", "author", "shared_url_domain"]
X.drop(labels=dropped_cols, axis=1, inplace=True)

In [23]:
X.head()

timestamp  feature1  feature2  followers  word_count  shared_url_count  \
0  1655713481254       100         0        999          25                 0   
1  1655743160254       100        -5          5           9                 0   
2  1655395750254       100        -5     454592          45                 0   
3  1654621088254       100         5      19348          10                 0   
4  1655754531254        45        -5        973          14                 0   

   is_reply  is_retweet  contains_video  contains_image  language_popularity  \
0         0           1               1               0               595244   
1         0           0               0               0               595244   
2         0           0               0               0               595244   
3         0           0               0               0                 1172   
4         0           1               0               1               595244   

   avg_engage_language  author_popularity  avg_engage_author  has_url  \
0          1654.123754                100           0.510000        0   
1          1654.123754                100           0.020000        0   
2          1654.123754                 99        4025.303030        0   
3           258.704778                 99           4.454545        0   
4          1654.123754                 94           2.872340        0   

   url_popularity  avg_engage_url  
0               0             0.0  
1               0             0.0  
2               0             0.0  
3               0             0.0  
4               0             0.0

In [22]:
X.describe()

timestamp       feature1       feature2     followers  \
count  6.354130e+05  635413.000000  635413.000000  6.354130e+05   
mean   1.654867e+12      66.005028      -0.325403  2.604219e+05   
std    7.300051e+08      38.953551       3.454980  2.303286e+06   
min    1.653286e+12       0.000000      -5.000000  0.000000e+00   
25%    1.654277e+12      29.000000      -5.000000  4.450000e+02   
50%    1.655001e+12      88.000000       0.000000  2.064000e+03   
75%    1.655534e+12     100.000000       0.000000  1.881600e+04   
max    1.655790e+12     100.000000       5.000000  1.087310e+08   

          word_count  shared_url_count       is_reply     is_retweet  \
count  635413.000000     635413.000000  635413.000000  635413.000000   
mean       17.832822          0.114296       0.199469       0.127155   
std        13.698307          0.423410       0.399601       0.333147   
min         0.000000          0.000000       0.000000       0.000000   
25%         8.000000          0.000000       0.000000       0.000000   
50%        14.000000          0.000000       0.000000       0.000000   
75%        25.000000          0.000000       0.000000       0.000000   
max       129.000000          4.000000       1.000000       1.000000   

       contains_video  contains_image  language_popularity  \
count   635413.000000   635413.000000        635413.000000   
mean         0.138028        0.189636        557820.167178   
std          0.344930        0.392013        144063.300916   
min          0.000000        0.000000             1.000000   
25%          0.000000        0.000000        595244.000000   
50%          0.000000        0.000000        595244.000000   
75%          0.000000        0.000000        595244.000000   
max          1.000000        1.000000        595244.000000   

       avg_engage_language  author_popularity  avg_engage_author  \
count        635413.000000      635413.000000      635413.000000   
mean           1617.903398          92.140109        1617.903398   
std             327.065817          17.685680        7903.916547   
min               0.000000           1.000000           0.000000   
25%            1654.123754          96.000000           1.783333   
50%            1654.123754          99.000000          37.179775   
75%            1654.123754         100.000000         526.787879   
max           16805.666667         107.000000      443919.000000   

             has_url  url_popularity  avg_engage_url  
count  635413.000000   635413.000000   635413.000000  
mean        0.078938       31.709606       85.825317  
std         0.269642      226.993412     1571.884062  
min         0.000000        0.000000        0.000000  
25%         0.000000        0.000000        0.000000  
50%         0.000000        0.000000        0.000000  
75%         0.000000        0.000000        0.000000  
max         1.000000     3037.000000   109872.485149

In [0]:
std_cols = ["timestamp","feature1","feature2","followers","word_count"]
std_scaler = preprocessing.MinMaxScaler().fit(X[std_cols])
X1 = std_scaler.transform(X[std_cols])

In [0]:
sparse_cols = ["shared_url_count", "language_popularity", "avg_engage_language","author_popularity",
               "avg_engage_author","url_popularity", "avg_engage_url"]
sparse_scaler = preprocessing.MaxAbsScaler().fit(X[sparse_cols])
X2 = sparse_scaler.transform(X[sparse_cols])

In [0]:
X[std_cols] = X1
X[sparse_cols] = X2

In [24]:
X.drop(labels=["timestamp",],axis = 1, inplace=True)

In [25]:
X.drop(labels=["has_url",],axis = 1, inplace=True)

In [26]:
scale_cols =  ["feature1","feature2","followers","word_count","shared_url_count", "language_popularity", 
         "avg_engage_language","author_popularity", "avg_engage_author","url_popularity", "avg_engage_url"]

minmax_scaler = preprocessing.MinMaxScaler().fit(X[scale_cols])
X[scale_cols] = minmax_scaler.transform(X[scale_cols])

/Users/FanJiang/anaconda/envs/python3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [49]:
scale_cols =  ["feature1","feature2","followers","word_count","shared_url_count", "language_popularity", 
         "avg_engage_language","author_popularity", "avg_engage_author","url_popularity", "avg_engage_url"]

In [27]:
X.head()

feature1  feature2     followers  word_count  shared_url_count  is_reply  \
0      1.00       0.5  9.187809e-06    0.193798               0.0         0   
1      1.00       0.0  4.598503e-08    0.069767               0.0         0   
2      1.00       0.0  4.180885e-03    0.348837               0.0         0   
3      1.00       1.0  1.779437e-04    0.077519               0.0         0   
4      0.45       0.0  8.948687e-06    0.108527               0.0         0   

   is_retweet  contains_video  contains_image  language_popularity  \
0           1               1               0             1.000000   
1           0               0               0             1.000000   
2           0               0               0             1.000000   
3           0               0               0             0.001967   
4           1               0               1             1.000000   

   avg_engage_language  author_popularity  avg_engage_author  url_popularity  \
0             0.098427           0.933962       1.148858e-06             0.0   
1             0.098427           0.933962       4.505326e-08             0.0   
2             0.098427           0.924528       9.067652e-03             0.0   
3             0.015394           0.924528       1.003459e-05             0.0   
4             0.098427           0.877358       6.470416e-06             0.0   

   avg_engage_url  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0

In [28]:
cols

Index(['engagement', 'timestamp', 'language', 'feature1', 'feature2',
       'followers', 'author', 'word_count', 'shared_url_count',
       'shared_url_domain', 'is_reply', 'is_retweet', 'contains_video',
       'contains_image'],
      dtype='object')

In [29]:
Data_test = D_test[cols.delete(0)]
Data_test.fillna("",inplace=True)
Data_test["language_popularity"] = Data_test.apply(lambda row: dict_language.get(row["language"],global_lang_avg_pop),axis = 1)
Data_test["avg_engage_language"] = Data_test.apply(lambda row: average_engage.get(row["language"],global_avg_engage_lang),axis = 1)
Data_test["author_popularity"] = Data_test.apply(lambda row: dict_author.get(row["author"],global_author_avg_pop),axis = 1)
Data_test["avg_engage_author"] = Data_test.apply(lambda row: avg_engage_author.get(row["author"],global_avg_engage_author),axis = 1)
Data_test["has_url"] = Data_test.apply(lambda row: 0 if row["shared_url_domain"] == "" else 1,axis = 1)
Data_test["url_popularity"] = Data_test.apply(lambda row: dict_url.get(row["shared_url_domain"],0) if row["has_url"] else 0,axis = 1)
Data_test["avg_engage_url"] = Data_test.apply(lambda row: avg_engage_url.get(row["shared_url_domain"],0) if row["has_url"] else 0,axis = 1)

boolean_cols = ["is_reply", "is_retweet", "contains_video", "contains_image"]
Data_test[boolean_cols] = Data_test[boolean_cols].astype(int)
dropped_cols = ["language", "author", "shared_url_domain"]
Data_test.drop(labels=dropped_cols, axis=1, inplace=True)
"""
Data_test1 = std_scaler.transform(Data_test[std_cols])
Data_test2 = sparse_scaler.transform(Data_test[sparse_cols])
Data_test[std_cols] = Data_test1
Data_test[sparse_cols] = Data_test2
"""
Data_test[scale_cols] = minmax_scaler.transform(Data_test[scale_cols])

Data_test.drop(labels=["timestamp",],axis = 1, inplace=True)
Data_test.drop(labels=["has_url",],axis = 1, inplace=True)

/Users/FanJiang/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/frame.py:4034: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)
/Users/FanJiang/anaconda/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/FanJiang/anaconda/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_inde

In [30]:
Data_test

feature1  feature2     followers  word_count  shared_url_count  \
0         1.00       0.0  3.275973e-05    0.046512              0.00   
1         0.13       0.0  1.251621e-04    0.054264              0.00   
2         1.00       0.5  4.589582e-04    0.093023              0.00   
3         0.95       0.0  2.696286e-04    0.170543              0.25   
4         1.00       0.5  1.416339e-06    0.023256              0.00   
5         1.00       0.0  1.563491e-07    0.054264              0.00   
6         1.00       0.5  2.501586e-05    0.186047              0.00   
7         1.00       0.0  2.336039e-05    0.093023              0.00   
8         0.17       0.5  6.042433e-06    0.046512              0.00   
9         0.38       0.0  1.060323e-03    0.085271              0.00   
10        1.00       0.0  6.520677e-06    0.100775              0.00   
11        0.38       0.5  1.248953e-05    0.255814              0.00   
12        0.58       0.0  1.595037e-04    0.100775              0.25   
13        1.00       0.0  1.351960e-06    0.209302              0.00   
14        0.00       0.5  1.186414e-05    0.116279              0.00   
15        0.41       0.5  2.187968e-05    0.333333              0.00   
16        0.34       0.5  6.196942e-05    0.217054              0.00   
17        0.87       0.5  1.167468e-03    0.201550              0.00   
18        0.50       1.0  3.110059e-04    0.093023              0.00   
19        1.00       0.5  3.264937e-06    0.147287              0.00   
20        0.50       1.0  1.839401e-08    0.100775              0.00   
21        1.00       0.0  1.747431e-07    0.356589              0.00   
22        0.29       0.5  9.197006e-07    0.062016              0.25   
23        1.00       1.0  6.325700e-05    0.162791              0.00   
24        0.39       0.5  6.401116e-06    0.178295              0.00   
25        0.77       0.5  8.154065e-05    0.379845              0.25   
26        1.00       0.5  4.147850e-06    0.062016              0.00   
27        1.00       0.5  4.256760e-03    0.131783              0.00   
28        1.00       0.5  4.231542e-05    0.093023              0.00   
29        1.00       0.0  7.536026e-05    0.077519              0.00   
...        ...       ...           ...         ...               ...   
2470      1.00       0.5  1.327128e-05    0.023256              0.00   
2471      0.73       0.5  5.251490e-06    0.155039              0.00   
2472      0.44       0.5  3.212965e-03    0.093023              0.00   
2473      0.50       0.5  1.182919e-04    0.054264              0.00   
2474      1.00       1.0  2.252347e-05    0.193798              0.00   
2475      0.82       0.5  1.397945e-05    0.209302              0.00   
2476      1.00       0.0  3.121648e-04    0.178295              0.00   
2477      0.00       0.5  1.074725e-03    0.147287              0.00   
2478      0.50       1.0  4.238900e-05    0.038760              0.00   
2479      1.00       0.5  2.874037e-03    0.240310              0.00   
2480      1.00       0.5  5.426233e-07    0.372093              0.00   
2481      0.09       1.0  1.283166e-04    0.279070              1.25   
2482      1.00       0.0  7.238043e-06    0.131783              0.00   
2483      0.56       1.0  7.100088e-06    0.116279              0.50   
2484      1.00       0.0  3.172967e-06    0.077519              0.00   
2485      0.69       1.0  1.105480e-05    0.124031              0.00   
2486      1.00       0.5  2.577921e-05    0.116279              0.00   
2487      1.00       1.0  4.384397e-03    0.286822              0.00   
2488      0.25       1.0  2.207281e-07    0.085271              0.00   
2489      0.25       0.5  1.168020e-05    0.038760              0.00   
2490      1.00       0.5  3.172967e-06    0.038760              0.00   
2491      1.00       0.5  1.076050e-05    0.046512              0.00   
2492      1.00       1.0  5.886819e-04    0.255814              0.00   
2493      1.00       1.0  7.541545e-06    0.03

In [ ]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators = 100, criterion='mse', verbose= True, ).fit(X, Y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


In [54]:
y_pred = RFR.predict(Data_test)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   10.2s finished


In [55]:
y_pred

array([   7.16610714,   94.99      , 3821.776     , ...,  137.82      ,
          0.        , 6294.95      ])

In [54]:
import xgboost
xgb = xgboost.XGBRegressor(max_depth=7, n_estimators=200)
xgb.fit(X,Y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=7, min_child_weight=1, missing=None, n_estimators=200,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [55]:
y_pred = xgb.predict(Data_test)

array([-13.81551056, -13.81551056,   8.15651023, ...,  10.37311611,
       -13.81551056,   9.61159664])

In [97]:
# log transform 
import xgboost
xgb = xgboost.XGBRegressor(n_estimators= 400, max_depth= 9, n_jobs = 4)
xgb.fit(X,np.log(Y+1e-6))
y_pred = xgb.predict(Data_test)
y_pred = np.exp(y_pred)

In [68]:
y_pred = xgb.predict(Data_test)
y_pred = np.exp(y_pred)

In [69]:
y_pred

array([2.3906806e+00, 4.3475571e+02, 1.1323616e+03, ..., 2.8203634e+01,
       1.0065970e-06, 8.9912605e-01], dtype=float32)

In [98]:
D_pred = pd.DataFrame(y_pred, columns=["engagement"])
D_pred.index +=1
D_pred.to_csv("submission_XGB_400_9_log.csv",index_label = "Id")

In [0]:
from google.colab import files
files.download('submission.csv')

In [0]:
new_X = X.drop(labels=["language_popularity","author_popularity", "url_popularity"],axis = 1)

In [80]:
num = [100,200,400]
depth = [5,7,9]

for n in num:
    for d in depth:
        xgb = xgboost.XGBRegressor(n_estimators = n, max_depth = d, n_jobs = 4)
        pred = cross_val_predict(xgb, X, np.log(Y + 1e-6), cv=5)
        print(n,d, MAE(np.exp(pred),Y))

10 5 6


In [83]:
pred

array([-13.759142 , -13.537834 ,   7.9405985, ...,   7.7445745,
       -12.337345 ,   9.465805 ], dtype=float32)

In [84]:
MAE(np.exp(pred), Y)

1103.9909854553175

In [74]:
import xgboost
xgb = xgboost.XGBRegressor(max_depth=7, n_estimators=200,n_jobs = 4)
xgb.fit(X_train,np.log(y_train+1e-6))
y_pred = xgb.predict(X_test)
MAE(y_test, np.exp(y_pred))

1075.5897296714982

In [75]:
xgb = xgboost.XGBRegressor(n_jobs = 4)
xgb.fit(X_train,np.log(y_train+1e-6))
y_pred = xgb.predict(X_test)
MAE(y_test, np.exp(y_pred))

1152.4350997759527

In [59]:
from sklearn.ensemble import RandomForestRegressor
num = [100,200,400]
depth = [5,7,9]

for n in num:
    for d in depth:
        RFR = RandomForestRegressor(n_estimators = n, max_depth = d, )
        l = cross_val_score(RFR, X, Y, scoring='neg_mean_absolute_error', cv=5)
        m =l.mean()
        print(n, d, m)

100 5 -1303.1202284474662
100 7 -1267.4712181904038
100 9 -1254.4365199906242
200 5 -1302.695449787905
200 7 -1267.7194750046933
200 9 -1252.6478957556403
400 5 -1302.9217695187226


KeyboardInterrupt: 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
num = [100,200,400]
depth = [5,7,9]
new_X = X.drop(labels=["language_popularity","author_popularity", "url_popularity"],axis = 1)

for n in num:
    for d in depth:
        RFR = RandomForestRegressor(n_estimators = n, max_depth = d, )
        l = cross_val_score(RFR, new_X, Y, scoring='neg_mean_absolute_error', cv=5)
        m =l.mean()
        print(n, d, m)

In [51]:
num = [100,200,400]
depth = [3,5,7]

for n in num:
    for d in depth:
        xgb = xgboost.XGBRegressor(max_depth=d, n_estimators=n)
        l = cross_val_score(xgb, X, Y, scoring='neg_mean_absolute_error', cv=5)
        m =l.mean()
        print(n, d, m)

100 3 -1318.7712382356121
100 5 -1275.1124933832325
100 7 -1262.1717964424795
200 3 -1320.7073751404391
200 5 -1278.2913930617601
200 7 -1266.5077456096994
400 3 -1316.2311289689044
400 5 -1282.7816364289386
400 7 -1273.8679861007133


In [52]:
xgb = xgboost.XGBRegressor()
l = cross_val_score(xgb, X, Y, scoring='neg_mean_absolute_error', cv=5)
m =l.mean()

In [53]:
print(m)

-1318.7712382356121


In [0]:
X.drop(labels=["has_url",],axis = 1, inplace=True)

In [31]:
X.head()

feature1  feature2     followers  word_count  shared_url_count  is_reply  \
0      1.00       0.5  9.187809e-06    0.193798               0.0         0   
1      1.00       0.0  4.598503e-08    0.069767               0.0         0   
2      1.00       0.0  4.180885e-03    0.348837               0.0         0   
3      1.00       1.0  1.779437e-04    0.077519               0.0         0   
4      0.45       0.0  8.948687e-06    0.108527               0.0         0   

   is_retweet  contains_video  contains_image  language_popularity  \
0           1               1               0             1.000000   
1           0               0               0             1.000000   
2           0               0               0             1.000000   
3           0               0               0             0.001967   
4           1               0               1             1.000000   

   avg_engage_language  author_popularity  avg_engage_author  url_popularity  \
0             0.098427           0.933962       1.148858e-06             0.0   
1             0.098427           0.933962       4.505326e-08             0.0   
2             0.098427           0.924528       9.067652e-03             0.0   
3             0.015394           0.924528       1.003459e-05             0.0   
4             0.098427           0.877358       6.470416e-06             0.0   

   avg_engage_url  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0

In [71]:
X_values = X.values
X_train, X_test, y_train, y_test = train_test_split(X_values,Y, test_size=0.2, random_state=42)

In [41]:
import xgboost
xgb = xgboost.XGBRegressor(max_depth=5, n_estimators=200)
xgb.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=200,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [42]:
y_pred = xgb.predict(X_test)

In [0]:
xgb.score(X_train,y_train)

0.4609951528723391

In [0]:
xgb.score(X_test,y_test)

0.3944564606059692

In [43]:
MAE(y_pred,y_test)

1260.966338753721

In [0]:
y_pred[100:120]

array([  395.44727 ,    76.29369 ,  5589.2036  ,    76.29369 ,
        5639.067   ,    16.873188,   -80.6459  ,    84.85982 ,
          94.416595,   -80.6459  ,   -99.634895,    76.29369 ,
         351.53516 ,   327.898   ,    27.77224 ,   156.53442 ,
         257.1179  ,   -80.6459  , 14315.04    ,   583.6589  ],
      dtype=float32)

In [0]:
y_test[100:120]

array([  336,     4,  5509,     0,     8,     0,     0,     6,     0,
           0,     0,    37,   304,     2,     1,     0,   117,     0,
       16566,   123])

In [0]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators = 100, verbose= True, ).fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:  5.5min finished


In [0]:
y_pred = RFR.predict(X_test)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    6.9s finished


In [0]:
RFR.score(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   26.7s finished


0.9089074535161289

In [0]:
RFR.score(X_test,y_test)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    6.9s finished


0.3640630957316382

In [0]:
MAE(y_pred,y_test)

1252.8560582150606

In [0]:
y_pred[100:120]

array([4.18840000e+02, 5.50000000e-01, 4.77804000e+03, 1.63000000e+00,
       3.63176000e+03, 2.00000000e-02, 0.00000000e+00, 3.50550000e+01,
       2.76666667e-01, 0.00000000e+00, 3.43333333e-01, 4.79800000e+01,
       4.05320000e+02, 1.07754000e+03, 3.48000000e+00, 0.00000000e+00,
       1.01794167e+02, 0.00000000e+00, 1.60238100e+04, 1.04341000e+03])

In [0]:
y_test[100:120]

array([  336,     4,  5509,     0,     8,     0,     0,     6,     0,
           0,     0,    37,   304,     2,     1,     0,   117,     0,
       16566,   123])

In [0]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [0]:
y_pred = reg.predict(X_test)

In [0]:
MAE(y_pred,y_test)

1635.5831644076763

In [0]:
reg.score(X_train,y_train)

0.3608150501866566

In [0]:
reg.score(X_test,y_test)

0.3477166125104979

In [0]:
from sklearn.neural_network import MLPRegressor
nn = MLPRegressor(hidden_layer_sizes=(256, 128, 64, 16), verbose=True).fit(X_train,y_train)

Iteration 1, loss = 70591370.59141135
Iteration 2, loss = 53046783.15302167
Iteration 3, loss = 52588482.49416848
Iteration 4, loss = 52436854.65307368
Iteration 5, loss = 52423860.41675160
Iteration 6, loss = 52357652.34496766
Iteration 7, loss = 52288476.89055861
Iteration 8, loss = 52204840.55687391
Iteration 9, loss = 52191867.08476962
Iteration 10, loss = 52203043.48621771
Iteration 11, loss = 52204566.45522118
Iteration 12, loss = 52070223.61319903
Iteration 13, loss = 52092306.45239532
Iteration 14, loss = 52097597.01515065
Iteration 15, loss = 51988251.08496352
Iteration 16, loss = 51937624.24972596
Iteration 17, loss = 52037636.13477058
Iteration 18, loss = 51867758.76228215
Iteration 19, loss = 51818939.33461963
Iteration 20, loss = 51743153.48001513
Iteration 21, loss = 51803380.46708936


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:568: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


In [0]:
y_pred = nn.predict(X_test)

In [0]:
MAE(y_pred,y_test)

1640.119569220309

In [0]:
X.shape

(635413, 15)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, BatchNormalization
from keras import activations

In [0]:
input_dim = 15
model = Sequential()
model.add(Dense(256, input_dim = 15,activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='relu'))
model.compile(
    loss=keras.losses.mean_absolute_error,
    optimizer=keras.optimizers.Adagrad(),
    metrics=['accuracy']
)
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 256)               4096      
_________________________________________________________________
dense_7 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_8 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_9 (Dense)              (None, 16)                1040      
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 17        
Total params: 46,305
Trainable params: 46,305
Non-trainable params: 0
_________________________________________________________________


In [0]:
batch_size = 256
epochs = 200
history = model.fit(X_train, y_train,
                         batch_size=batch_size,
                         epochs=epochs,
                         verbose=1,
                         validation_data=(X_test, y_test))
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 508330 samples, validate on 127083 samples
Epoch 1/200
508330/508330 [==============================] - 20s 40us/step - loss: 1193.2902 - acc: 0.3136 - val_loss: 1173.0563 - val_acc: 0.3071
Epoch 2/200
508330/508330 [==============================] - 20s 39us/step - loss: 1178.2068 - acc: 0.3139 - val_loss: 1156.8293 - val_acc: 0.3245
Epoch 3/200
508330/508330 [==============================] - 20s 39us/step - loss: 1165.8309 - acc: 0.3140 - val_loss: 1144.7819 - val_acc: 0.3242
Epoch 4/200
508330/508330 [==============================] - 20s 39us/step - loss: 1156.7747 - acc: 0.3146 - val_loss: 1146.7910 - val_acc: 0.2968
Epoch 5/200
508330/508330 [==============================] - 20s 40us/step - loss: 1150.7602 - acc: 0.3150 - val_loss: 1129.6018 - val_acc: 0.3168
Epoch 6/200
508330/508330 [==============================] - 20s 39us/step - loss: 1146.3995 - acc: 0.3147 - val_loss: 1126.4040 - val_acc: 0.3159
Epoch 7/200
508330/508330 [==============================] - 21s 4

KeyboardInterrupt: ignored

In [0]:
batch_size = 256
epochs = 200
history = model.fit(X_values, Y,
                         batch_size=batch_size,
                         epochs=epochs,
                         verbose=1,
                         )

Epoch 1/200
635413/635413 [==============================] - 12s 19us/step - loss: 1116.6540 - acc: 0.3065
Epoch 2/200
635413/635413 [==============================] - 12s 18us/step - loss: 1116.4964 - acc: 0.3069
Epoch 3/200
635413/635413 [==============================] - 12s 19us/step - loss: 1116.3985 - acc: 0.3067
Epoch 4/200
635413/635413 [==============================] - 12s 19us/step - loss: 1116.3235 - acc: 0.3068
Epoch 5/200
635413/635413 [==============================] - 12s 18us/step - loss: 1116.2138 - acc: 0.3068
Epoch 6/200
635413/635413 [==============================] - 12s 19us/step - loss: 1116.1073 - acc: 0.3067
Epoch 7/200
635413/635413 [==============================] - 12s 18us/step - loss: 1116.0358 - acc: 0.3069
Epoch 8/200
635413/635413 [==============================] - 12s 19us/step - loss: 1115.9587 - acc: 0.3069
Epoch 9/200
635413/635413 [==============================] - 12s 18us/step - loss: 1115.8705 - acc: 0.3068
Epoch 10/200
635413/635413 [=========

KeyboardInterrupt: ignored

In [0]:
y_pred = model.predict(Data_test)

In [0]:
MAE(y_pred,y_test)

1106.6741699329218

In [0]:
y_pred[200:220]

array([[0.0000000e+00],
       [4.6323601e+01],
       [0.0000000e+00],
       [2.9771949e+04],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.0430628e+01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [7.3187904e+01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.3232985e+02],
       [0.0000000e+00]], dtype=float32)

In [0]:
y_test[200:220]

array([   21,    10,   161, 10393,     0,     0,     0,     2,     9,
           0,     0,     2,     0,     5,     0,     4,     0,    17,
         348,     0])

In [0]:
word_vector = D_train.iloc[:,14:]

In [0]:
m,n = word_vector.shape
word_vector.shape

(5536, 1024)

In [0]:
word_vector.describe()

V1           V2  ...        V1023        V1024
count  5536.000000  5536.000000  ...  5536.000000  5536.000000
mean      0.011405     0.001566  ...     0.016549     0.027529
std       0.010882     0.005966  ...     0.009375     0.012155
min      -0.008949    -0.002177  ...    -0.006794    -0.017138
25%       0.003204    -0.000026  ...     0.010491     0.019774
50%       0.009172    -0.000007  ...     0.015787     0.028600
75%       0.016819     0.000262  ...     0.021814     0.035927
max       0.062851     0.110767  ...     0.089095     0.071600

[8 rows x 1024 columns]

In [0]:
train_pred = model.predict(X_values[-m:])
residuals = Y[-m:] - np.squeeze(train_pred)

In [0]:
residual_X = word_vector.values
residual_Y = residuals
resX_train, resX_test, resy_train, resy_test = train_test_split(residual_X,residual_Y, test_size=0.2, random_state=42)

In [0]:
residuals.shape

(5536,)

In [0]:
Y[-m:].shape

(5536,)

In [0]:
input_dim = n
residual_model = Sequential()
residual_model.add(Dense(256, input_dim = input_dim,activation='relu'))
residual_model.add(Dense(128, activation='relu'))
residual_model.add(Dense(64, activation='relu'))
residual_model.add(Dense(16, activation='relu'))
residual_model.add(Dense(1))
residual_model.compile(
    loss=keras.losses.mean_absolute_error,
    optimizer=keras.optimizers.Adagrad(),
    metrics=['accuracy']
)
residual_model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 256)               262400    
_________________________________________________________________
dense_32 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_33 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_34 (Dense)             (None, 16)                1040      
_________________________________________________________________
dense_35 (Dense)             (None, 1)                 17        
Total params: 304,609
Trainable params: 304,609
Non-trainable params: 0
_________________________________________________________________


In [0]:
batch_size = 128
epochs = 100
history_res = residual_model.fit(resX_train, resy_train,
                         batch_size=batch_size,
                         epochs=epochs,
                         verbose=1,
                         validation_data=(resX_test, resy_test))
score_res = residual_model.evaluate(resX_test, resy_test, verbose=0)
print('Test loss:', score_res[0])
print('Test accuracy:', score_res[1])

Train on 4428 samples, validate on 1108 samples
Epoch 1/100
4428/4428 [==============================] - 1s 124us/step - loss: 13139.4847 - acc: 0.0400 - val_loss: 10314.1405 - val_acc: 0.0659
Epoch 2/100
4428/4428 [==============================] - 0s 47us/step - loss: 13118.1722 - acc: 0.1527 - val_loss: 10289.8195 - val_acc: 0.1949
Epoch 3/100
4428/4428 [==============================] - 0s 47us/step - loss: 13096.9084 - acc: 0.1893 - val_loss: 10278.3699 - val_acc: 0.2148
Epoch 4/100
4428/4428 [==============================] - 0s 53us/step - loss: 13085.9447 - acc: 0.2037 - val_loss: 10273.7762 - val_acc: 0.2175
Epoch 5/100
4428/4428 [==============================] - 0s 49us/step - loss: 13077.4115 - acc: 0.2096 - val_loss: 10272.7077 - val_acc: 0.2085
Epoch 6/100
4428/4428 [==============================] - 0s 49us/step - loss: 13070.0804 - acc: 0.2089 - val_loss: 10267.8921 - val_acc: 0.2220
Epoch 7/100
4428/4428 [==============================] - 0s 50us/step - loss: 13062.764

In [0]:
batch_size = 128
epochs = 100
history_res = residual_model.fit(residual_X, residual_Y,
                         batch_size=batch_size,
                         epochs=epochs,
                         verbose=1,
                        )

Epoch 1/100
5536/5536 [==============================] - 1s 112us/step - loss: 12571.9739 - acc: 0.0569
Epoch 2/100
5536/5536 [==============================] - 0s 49us/step - loss: 12547.1820 - acc: 0.1768
Epoch 3/100
5536/5536 [==============================] - 0s 56us/step - loss: 12529.4626 - acc: 0.2030
Epoch 4/100
5536/5536 [==============================] - 0s 54us/step - loss: 12521.0830 - acc: 0.2101
Epoch 5/100
5536/5536 [==============================] - 0s 52us/step - loss: 12513.6227 - acc: 0.2142
Epoch 6/100
5536/5536 [==============================] - 0s 51us/step - loss: 12507.0535 - acc: 0.2160
Epoch 7/100
5536/5536 [==============================] - 0s 52us/step - loss: 12501.7205 - acc: 0.2177
Epoch 8/100
5536/5536 [==============================] - 0s 54us/step - loss: 12493.7923 - acc: 0.2197
Epoch 9/100
5536/5536 [==============================] - 0s 48us/step - loss: 12489.0833 - acc: 0.2220
Epoch 10/100
5536/5536 [==============================] - 0s 52us/step -

In [0]:
resy_testpred = residual_model.predict(resX_test)

In [0]:
MAE(resy_testpred, resy_test)

10846.635967175682

In [0]:
resy_testpred[100:120]

array([[-3.3938926e-01],
       [-9.1224238e-02],
       [ 8.3089783e+02],
       [ 1.9246199e+04],
       [ 2.0349256e+04],
       [-3.5304469e-01],
       [ 1.6441660e+01],
       [-3.6395365e-01],
       [-2.7986246e-01],
       [ 7.2726001e+03],
       [ 1.6749376e+01],
       [ 1.8580405e+02],
       [-3.2087916e-01],
       [ 4.1314194e+03],
       [-4.0914243e-01],
       [-3.0935699e-01],
       [ 3.3513664e+04],
       [ 9.9610068e+03],
       [ 1.4283991e+04],
       [ 3.1937469e+01]], dtype=float32)

In [0]:
resy_test[100:120]

array([ 0.00000000e+00,  0.00000000e+00, -3.61563242e+04,  9.73794922e-01,
        3.04422574e+05, -1.62902355e+00,  1.20000000e+01,  1.34611055e+02,
        0.00000000e+00,  2.40000000e+01,  8.74454269e+01, -7.42779541e+02,
        0.00000000e+00,  1.62185856e+04, -2.65790272e+00,  1.48800000e+03,
        9.53010547e+03,  3.59818354e+02,  5.81826431e+03,  3.54207712e+03])

In [0]:
word_vector_test = D_test.iloc[:,14:]

In [0]:
residual_test_pred = residual_model.predict(word_vector_test.values)

In [0]:
residual_test_pred.shape

(2500, 1)

In [0]:
y_pred = y_pred + residual_test_pred